/**
 * SelfView bilingual copy (F-A10-lite · zh + en inline, mirrors profileContent).
 *
 * Errors dict keys are self-view-specific (NOT Record<CandidateApiErrorCode>):
 * SESSION_INCOMPLETE is a new Backend code (B-A10-lite) that's not in the
 * candidate-api union. Lookup falls back to INTERNAL_ERROR so any unknown
 * server-side code still produces a candidate-friendly message.
 */

import type { BilingualText } from '../../lib/bilingual.js';

export type SelfViewErrorKey =
  | 'NOT_FOUND'
  | 'SESSION_INCOMPLETE'
  | 'VALIDATION_ERROR'
  | 'INTERNAL_ERROR';

export interface SelfViewContent {
  readonly pageTitle: BilingualText;
  readonly subtitle: (completedAtLocal: string) => BilingualText;
  readonly ethicsNote: BilingualText;
  readonly capabilitySectionTitle: BilingualText;
  readonly radarSectionTitle: BilingualText;
  readonly strengthLabels: {
    readonly strong: BilingualText;
    readonly medium: BilingualText;
    readonly weak: BilingualText;
  };
  readonly footer: BilingualText;
  readonly loading: BilingualText;
  readonly errorTitle: BilingualText;
  readonly errors: Readonly<Record<SelfViewErrorKey, BilingualText>>;
  readonly urlMissingParams: BilingualText;
}

export const SELF_VIEW_CONTENT: SelfViewContent = {
  pageTitle: { zh: '你的能力画像', en: 'Your Capability Profile' },
  subtitle: (completedAtLocal: string) => ({
    zh: `面试于 ${completedAtLocal} 完成`,
    en: `Interview completed ${completedAtLocal}`,
  }),
  ethicsNote: {
    zh: '此页仅你本人可见 · 企业后台不可访问此链接。',
    en: 'This page is private to you · the company cannot access this link.',
  },
  capabilitySectionTitle: { zh: '能力画像', en: 'Capability Profiles' },
  radarSectionTitle: { zh: '六维相对强弱', en: 'Dimension Relative Strength' },
  strengthLabels: {
    strong: { zh: '强', en: 'Strong' },
    medium: { zh: '中', en: 'Medium' },
    weak: { zh: '弱', en: 'Weak' },
  },
  footer: {
    zh: '本报告由 CodeLens 生成 · 请妥善保存此链接 · 不可通过公司后台重新获取。',
    en: 'Report generated by CodeLens · keep this link safe · cannot be re-fetched from company admin.',
  },
  loading: { zh: '加载中…', en: 'Loading…' },
  errorTitle: { zh: '无法加载', en: 'Unable to load' },
  errors: {
    NOT_FOUND: {
      zh: '链接无效或已过期,请联系 HR 重新获取。',
      en: 'Link invalid or expired — please contact HR to request a new one.',
    },
    SESSION_INCOMPLETE: {
      zh: '你的考试尚未完成,请先完成考试再回到此页面。',
      en: 'Your exam is not yet complete — please finish it first, then return to this page.',
    },
    VALIDATION_ERROR: {
      zh: '请求格式异常,请联系 HR。',
      en: 'Request format error — please contact HR.',
    },
    INTERNAL_ERROR: {
      zh: '服务端暂时无法处理请求,请稍后重试。如问题持续,请联系 HR。',
      en: 'The server cannot process the request right now — please retry shortly. If the problem persists, contact HR.',
    },
  },
  urlMissingParams: {
    zh: '链接参数缺失,请确认你打开的是完整的自查链接。',
    en: 'Link parameters missing — please make sure you opened the full self-view link.',
  },
};
